import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import AIChatButton from "../components/AiChat/AiChatButton";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <Header />
          <div className="mx-auto flex min-h-[90vh] w-[80%] flex-1 flex-col">
            <Toaster />
            {children}
            <AIChatButton />
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
